experiment:
    id: unconditional_given_means_bg_only

##Data
data:
    data_dir: '/storage_local/kwang/nuscenes/raw'
    splats_dir: '/storage_local/kwang/nuscenes/framewise_mini/'
    resolution: 0.01
    dataloader: 'NuScenes'
    num_lidar_points: 1000
    horizontal_range: [-100., 100.]
    vertical_range: [-15., 5.]

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 4
    max_epoch: 100
    lr: 0.001
    batch_size: 1
    decay_lr: 1.0e-4

diff:
    color:
        beta_start: 1.e-6
        beta_end: 5.e-3
        beta_func: 'linear'
    opacity:
        beta_start: 1.e-6
        beta_end: 5.e-3
        beta_func: 'linear'
    scale:
        beta_start: 1.e-6
        beta_end: 5.e-3
        beta_func: 'linear'
    quat_0:
        beta_start: 1.e-6
        beta_end: 5.e-3
        beta_func: 'linear'
    quat_rest:
        beta_start: 1.e-6
        beta_end: 5.e-3
        beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.

##Network
model:
    in_dim: 14
    out_dim: 11

log:
    wandb: True
